spring.application.name=backend

# Puerto de la API
server.port=8080

# Conexión a SQLite (Va a crear el archivo en la carpeta raíz de tu proyecto)
spring.datasource.url=jdbc:sqlite:base_datos_nakel.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Ya no se necesitaa usuario y contraseña porque es un archivo local!

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
