spring.application.name=backend

# Puerto de la API
server.port=8080

# ? CONEXIÓN PRO A SQLITE (Guarda la BD en Documentos/NakelSoftware)
spring.datasource.url=jdbc:sqlite:${user.home}/Documents/NakelSoftware/base_datos_nakel.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Ya no se necesita usuario y contraseña porque es un archivo local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de email (Si no lo usás ahora, no molesta)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu_correo@gmail.com
spring.mail.password=tu_clave_de_aplicacion_de_16_letras
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true